spring:
  application:
    name: user-service

  config:
    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:postgresql://localhost:5433/retail_user_db?TimeZone=UTC
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: chavvaabhishek20@gmail.com
    password: csxvonlmyjgoxnhw

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:

    bootstrap-servers: localhost:9092

    consumer:

      group-id: retail-group

      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

      properties:

        spring.json.trusted.packages: "*"

    producer:

      key-serializer: org.apache.kafka.common.serialization.StringSerializer

      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    admin:

      auto-create: true

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

razorpay:
  key-id: rzp_test_T58HGFXCgmQyz8
  key-secret: xCH76XyeJzJDOGG4zu4DiEle

springdoc:
  api-docs:
    path: /api-docs

  swagger-ui:
    path: /swagger-ui.html
